version: "3.9"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    volumes:
      - "influxdb:/var/lib/influxdb2"
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "adminadmin"
      DOCKER_INFLUXDB_INIT_BUCKET: "JFR"
      DOCKER_INFLUXDB_INIT_ORG: "NS"
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
volumes:
  influxdb:
  grafana-storage: